install.packages("readr")
install.packages("ggplot2")
install.packages("dplyr")
install.packages("tidyr")
install.packages("GGally")
install.packages("stringr")
install.packages("ggstats")
install.packages("MASS")

library(readr)
library(ggplot2)
library(dplyr)
library(tidyr)
library(cowplot)
library(GGally)
library(stringr)
library(ggstats)
library(MASS)

